name: chat
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: '>=2.19.0 <3.0.0'

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter
  card_swiper: ^2.0.4
  flutter_screenutil: ^5.6.1
  provider: ^6.0.5
  http: ^0.13.5
  flutter_html: ^2.2.1
  google_fonts: ^4.0.3
  google_maps_flutter: ^2.2.3
  geolocator: ^9.0.2
  geocoding: ^2.0.5
  fluttertoast: ^8.1.3
  page_transition: ^2.0.9
  circular_rotation: ^0.0.1
  circular_motion: ^0.0.3
  shimmer: ^2.0.0
  widget_circular_animator: ^1.0.0
  flutter_easyloading: ^3.0.5
  material_dialogs: ^1.1.4
  permission_handler: ^10.2.0
  firebase_auth: ^4.2.8
  google_sign_in: ^6.0.0
  firebase_core: ^2.6.1
  cloud_firestore: ^4.4.2
  fancy_shimmer_image: ^2.0.2
  rotated_corner_decoration: ^2.1.0+1
  back_button_interceptor: ^6.0.2
  circular_menu: ^2.0.1
  cupertino_icons: ^1.0.2
  avatar_glow: ^2.0.2
  glass: ^1.0.1+1
  google_nav_bar: ^5.0.6
  line_icons: ^2.0.1
  flutter_neumorphic: ^3.2.0
  gradient_borders: ^1.0.0
  dropdown_button2: ^1.9.4
  im_stepper: ^1.0.1+1
  roundcheckbox: ^2.0.5
  animated_item_picker: ^2.0.0
  stepper_counter_swipe: ^1.0.2
  woocommerce_api: ^0.1.0
  sliding_switch: ^1.1.0
  day_night_time_picker: ^1.2.0+1
  google_maps_widget: ^1.0.5+1
  syncfusion_flutter_maps: ^20.4.53
  maps_curved_line: ^1.0.2
  flutter_polyline_points: ^1.0.0
  vertical_card_pager: ^1.5.0
  folding_cell: ^1.0.2
  stacked_card_carousel: ^0.0.4
  tap_to_expand: ^0.6.1
  flutter_spinkit: ^5.1.0
  animation_director: ^0.1.1
  widget_and_text_animator: ^1.0.9
  flutter_cool_card_swiper: ^0.0.4
  card_stack_widget: ^0.1.5
  swipe_deck: ^1.1.0
  confetti: ^0.7.0
  card_slider: ^1.0.5
  ticket_widget: ^0.0.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.0.13
  cached_network_image: ^3.2.3
  animated_text_kit: ^4.2.2
  font_awesome_flutter: ^10.4.0
  simple_icons: ^7.10.0
  fluentui_system_icons: ^1.1.191
  food_icons: ^0.0.6
  custom_clippers: ^2.0.0
  swipe_to: ^1.0.2
  flutter_phone_direct_caller: ^2.1.1
  flutter_staggered_grid_view: ^0.6.2
  url_launcher: ^6.1.10
  carousel_slider: ^4.2.1
  fl_chart: ^0.61.0
  syncfusion_flutter_charts: ^20.4.54
  uuid: ^3.0.7
  flutter_chat_bubble: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
